### ISSUE TITLE
Crash (Actor type 'zep' does not define a quantized body orientation)

### ISSUE THREAD

**Issue by steadyfield** [phrohdoh/OpenRA#20]
``` csharp
Red Alert 2 Mod at Version {DEV_VERSION}
on map 8ad775a6b69b16351ff478f464c90dcca1e075fc (Breakaway by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Actor type 'zep' does not define a quantized body orientation.
   at OpenRA.Mods.Common.Traits.BodyOrientation.<>c__DisplayClass3.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.Mods.Common.Traits.BodyOrientation.QuantizeOrientation(Actor self, WRot orientation)
   at OpenRA.Mods.Common.Traits.WithVoxelBody.<>c__DisplayClass9.<.ctor>b__1()
   at OpenRA.Graphics.VoxelRenderer.RenderAsync(WorldRenderer wr, IEnumerable`1 voxels, WRot camera, Single scale, Single[] groundNormal, WRot lightSource, Single[] lightAmbientColor, Single[] lightDiffuseColor, PaletteReference color, PaletteReference normals, PaletteReference shadowPalette) in d:\git\OpenRA-ra2-master\OpenRA.Game\Graphics\VoxelRenderer.cs:Line 111
   at OpenRA.Mods.Common.Graphics.VoxelRenderable.FinalizedVoxelRenderable..ctor(WorldRenderer wr, VoxelRenderable voxel)
   at OpenRA.Mods.Common.Graphics.VoxelRenderable.PrepareRender(WorldRenderer wr)
   at OpenRA.Graphics.WorldRenderer.<GenerateRenderables>b__6(IRenderable r) in d:\git\OpenRA-ra2-master\OpenRA.Game\Graphics\WorldRenderer.cs: 122
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OpenRA.Graphics.WorldRenderer.GenerateRenderables() in d:\git\OpenRA-ra2-master\OpenRA.Game\Graphics\WorldRenderer.cs:Line 121
   at OpenRA.Graphics.WorldRenderer.Draw() in d:\git\OpenRA-ra2-master\OpenRA.Game\Graphics\WorldRenderer.cs:Line 138
   at OpenRA.Game.RenderTick() in d:\git\OpenRA-ra2-master\OpenRA.Game\Game.cs:Line 515
   at OpenRA.Game.Loop() in d:\git\OpenRA-ra2-master\OpenRA.Game\Game.cs:Line 643
   at OpenRA.Game.Run() in d:\git\OpenRA-ra2-master\OpenRA.Game\Game.cs:Line 661
   at OpenRA.Program.Run(String[] args) in d:\git\OpenRA-ra2-master\OpenRA.Game\Support\Program.cs:Line 117
   at OpenRA.Program.Main(String[] args) in d:\git\OpenRA-ra2-master\OpenRA.Game\Support\Program.cs:Line 39
```

**Comment by phrohdoh** [comment]
@penev92 is this still an issue?
I know it existed for quite some time.
