### ISSUE TITLE
Exception of type `System.InvalidOperationException`: Cannot locate type: HelicopterInfo

### ISSUE THREAD

**Issue by grasmanek94** [phrohdoh/OpenRA#22]
Just tried the mod out today, downloaded, make dependencies, make all, copy ra2 mod folder into mods, copy all .mix files from red alert 2 install directory to the openra documents contents\ra2 directory, copy any missing files from original openra directory to openra2 directory (skipping any existing files), launch, load red alert 2 mod and this:

```
Red Alert 2 Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Cannot locate type: HelicopterInfo
   at OpenRA.ObjectCreator.<.cctor>b__13(String s) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\ObjectCreator.cs:line 46
   at OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\ObjectCreator.cs:line 58
   at OpenRA.ObjectCreator.CreateObject[T](String className) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\ObjectCreator.cs:line 50
   at OpenRA.Game.CreateObject[T](String name) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 737
   at OpenRA.ActorInfo.LoadTraitInfo(String traitName, MiniYaml my) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\ActorInfo.cs:line 112
   at OpenRA.ActorInfo..ctor(String name, MiniYaml node, Dictionary`2 allUnits) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\ActorInfo.cs:line 55
   at OpenRA.RulesetCache.<Load>b__0(MiniYamlNode k, Dictionary`2 y) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\RulesetCache.cs:line 64
   at OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__10(MiniYamlNode wkv, Dictionary`2 wyy) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\RulesetCache.cs:line 113
   at OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__14(MiniYamlNode kv) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\RulesetCache.cs:line 121
   at OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Exts.cs:line 365
   at OpenRA.RulesetCache.LoadYamlRules[T](Dictionary`2 itemCache, String[] files, List`1 nodes, Func`3 f) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\RulesetCache.cs:line 121
   at OpenRA.RulesetCache.Load(Map map) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\GameRules\RulesetCache.cs:line 62
   at OpenRA.ModData.<.ctor>b__2() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\ModData.cs:line 77
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.ModData.get_DefaultRules() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\ModData.cs:line 35
   at OpenRA.Map.<PostInit>b__b() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Map\Map.cs:line 409
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at OpenRA.Map.PreloadRules() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Map\Map.cs:line 532
   at OpenRA.ModData.PrepareMap(String uid) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\ModData.cs:line 170
   at OpenRA.Game.StartGame(String mapUID, WorldType type) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 149
   at OpenRA.Game.LoadShellMap() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 383
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 339
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<>c__DisplayClass27.<LoadMod>b__25()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Primitives\ActionQueue.cs:line 52
   at OpenRA.Game.LogicTick() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 506
   at OpenRA.Game.Loop() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 638
   at OpenRA.Game.Run() in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Game.cs:line 678
   at OpenRA.Program.Run(String[] args) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Support\Program.cs:line 117
   at OpenRA.Program.Main(String[] args) in d:\Desktop\OpenRA-ra2-master\OpenRA.Game\Support\Program.cs:line 39
```

**Comment by penev92** [comment]
Sorry, at the moment the mod is not in working condition due to the engine changes happening to OpenRA. We'll try to update it so it works with the latest version of OpenRA after OpenRA gets a playtest out.

**Comment by phrohdoh** [comment]
Hey, thanks for trying out the mod!
Unfortunately as penev said I have neglected this quite a bit due to work and other areas of interest.
There are a few people putting in good work to get it back on track.

Stay tuned!
