### ISSUE TITLE
Crashed When Loading RA2 Model

### ISSUE THREAD

**Issue by zhaozhang233** [phrohdoh/OpenRA#85]
I use the same way you mentioned here (https://github.com/Phrohdoh/oramod-ra2/wiki/Content-installation), installed contents from RA2 cd1, but when choosing RA2 mod, openra crashed, and I found information below:

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.ObjectCreator..ctor(Manifest manifest)
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<LoadMod>c__AnonStorey1.<>m__0()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int32 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

I'm not familiar with C# so could you please help me find out what's going on? Thanks

**Comment by phrohdoh** [comment]
@zhaozhang233 Did you install RA2 into an existing OpenRA installation?
If so, that won't work. You have to build the engine from source to play this version.
